import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Brands from '../components/Brands'
import WatchVideo from '../components/WatchVideo'
import FeaturedWork from '../components/FeaturedWork'
import Services from '../components/Services'
import Reviews from '../components/Reviews'
import Info from '../components/Info'
import Blog from '../components/Blog'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by furkanyucel" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Brands />
      <WatchVideo />
      <FeaturedWork />
      <Services />
      <Reviews />
      <Info />
      <Blog />
      <Footer />
    </div>
  )
}
