import Head from 'next/head'
import Image from 'next/image'
import Brands from './components/Brands'
import Header from './components/Header'
import Hero from './components/Hero'
import Brand from './components/Brands'
import WatchVideo from './components/WatchVideo'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Brand />
      <WatchVideo />
    </div>
  )
}
